### ISSUE TITLE
"Dataset Mismatch" -- unable to run data generation

### ISSUE THREAD

**Issue by tejas-gokhale** [facebookresearch/daqa#1]
Hello,

I'm running `generate_audio.py`.
However, the following line of code:
`assert len(lst_events) == len(lst_events_wav), 'Dataset mismatch.'`
ends up in error, since `len(lst_events) = 400` and `len(lst_events_wav) = 182`

Also, in the script for running generate_audio.py here: https://github.com/facebookresearch/daqa/blob/master/daqa-gen/README.md,  the following is used `--events $daqa_gen_local/events` with `daqa_gen_local=../daqa-gen-local`.

However there is no such directory called data_gen_local.
`data-audio.gz.tar` contains two subdirectories `rawa` and `backgrounds` .  Are "raws" and "events" equivalent?

I would highly appreciate if you could look into this, or if possible -- provide a download link for the dataset you generated for your experiments.

Thanks!

**Comment by haythamfayek** [comment]
Hi Tejas—We are unable to release all 400 events due to copyright matters. We released events we recorded (`raws`) but you will have to get other events (`urls`) listed in `daqa_sources.json` on your own from the provided urls. Both `raws` and `urls` should amount to all 400 events.

**Comment by tejas-gokhale** [comment]
Thanks for the reply Haytham! I will try that.
